### ISSUE TITLE
Is minimum font size supported?

### ISSUE THREAD

**Issue by leonardos-eb** [tobihagemann/THLabel#41]

**Comment by tobihagemann** [comment]
Neither `minimumFontSize` nor `minimumScaleFactor` is considered in THLabel. IIRC, it can't be easily implemented, because Core Text doesn't support these kinds of mechanisms.

Someone has linked an interesting project in issue #40: https://github.com/tbaranes/FittableFontLabel

It has an interesting approach on how this could be achieved using binary search. However, due to time constraints I probably won't pursue this anytime soon.
